powers:
  shockwave:
    item_name: ยง5Onde de choc
    max_radius: 5	# The shockwave size
    speed: 2	# How many ticks for a one block propagation
    damage: 10
  bunker:
    item_name: ยง5Bunker
    radius: 2	# The bunker size
    speed: 2	# How many ticks before the next block in the animation
    life: 400	# How many ticks before destroying the bunker