name: RoleCraft
version: 1.0
author: MartDel
main: fr.martdel.rolecraft.RoleCraft
api-version: 1.13

commands:
  # Public commands
  switch:
    description: Permet aux admins de s'OP facilement

  # Powers
  power:
    description: Get a power item
    permission: power.use
  # For tests
  test:
    permission: test.use